### ISSUE TITLE
Can't make it work with webpack

### ISSUE THREAD

**Issue by Growiel** [nabble/unveil2#13]
HI!

Trying to get this, and its predecessor, to work with webpack but to no avail.

I get: `Uncaught TypeError: $ is not a function.`

I also tried with the imports-loader module, but still not working.
I also tried to use the unveil2 npm package, same result.

This library is the only one preventing me from moving to Webpack...

Thanks.

**Comment by hongaar** [comment]
I'm afraid I don't have any experience with webpack, but it seems that it's missing jQuery.
