### ISSUE TITLE
width/height markup attributes

### ISSUE THREAD

**Issue by BeatLaG** [nabble/unveil2#14]
I´m wondering about the best method to add a preloader indicator for each image. I though that adding a width & height for each element would be enough, but it seems that even if I add the sizes the images are scaled somehow from 0 to width (if you add css transforms you can check this better).

Then, which should be the best method to preserve the layout sizes before unveil images? Could you please suggest a good method to add a preloader indicator vertically/horizontally centered within the item  area?

Thanks!

**Comment by hongaar** [comment]
I don't know exactly what you mean. Something like this? http://jsfiddle.net/hongaar/bpzfgudm/3/

**Comment by BeatLaG** [comment]
I didn´t realize about the loading class. That´s perfect, otherwise and due to the way I´m loading the contents (css transitions), I was not able to add a background loader.

Thanks Joram!
