### ISSUE TITLE
Replace grunt-contrib-qunit

### ISSUE THREAD

**Issue by vogdb** [nabble/unveil2#26]
Hi @hongaar !
grunt-contrib-qunit uses a very very outdated qunit 1.18.0 which does not support even nesting inside `Qunit.module`. Its updating seems to be postponed gruntjs/grunt-contrib-qunit#123. What do you think about grunt-contrib-jasmine?
Offtopic. Wdyt about changing grunt to gulp?

**Comment by vogdb** [comment]
Also we can not use `qunit-fixture` feature cause it has unacceptable styles for purposes of this library.

**Comment by hongaar** [comment]
I have no experience with jasmine, but I'd be more than happy to accept a PR for this. Also the tests use only jQuery 2, maybe it'd be nice to also test with jQuery 3?

Switching from grunt to gulp is certainly nice to have, but I think the disadvantages of Grunt (mainly speed) are not really a problem in this repo?

**Comment by vogdb** [comment]
> I have no experience with jasmine, but I'd be more than happy to accept a PR for this.

Don't worry I will do it but I'm not sure about jasmine. I will quickly look over all popular test libraries.

> Switching from grunt to gulp is certainly nice to have, but I think the disadvantages of Grunt (mainly speed) are not really a problem in this repo?

The main disadvantage here that grunt receive less support than gulp. For example grunt-contrib-qunit which kind of stucked in its support and currently outdated.

**Comment by vogdb** [comment]
in favor of #28
